//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class drivingLicense
{

    private string nameField;

    private string fatherNameField;

    private string addressField;

    private int pinField;

    private string bgField;

    private string dOBField;

    private string countryNameField;

    private string stateNameField;

    private string dLNumberField;

    private string issuingIdField;

    private string dOIField;

    private string validTillField;

    private string cOV1Field;

    private string cOV2Field;

    /// <remarks/>
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    public string FatherName
    {
        get
        {
            return this.fatherNameField;
        }
        set
        {
            this.fatherNameField = value;
        }
    }

    /// <remarks/>
    public string Address
    {
        get
        {
            return this.addressField;
        }
        set
        {
            this.addressField = value;
        }
    }

    /// <remarks/>
    public int Pin
    {
        get
        {
            return this.pinField;
        }
        set
        {
            this.pinField = value;
        }
    }

    /// <remarks/>
    public string BG
    {
        get
        {
            return this.bgField;
        }
        set
        {
            this.bgField = value;
        }
    }

    /// <remarks/>
    public string DOB
    {
        get
        {
            return this.dOBField;
        }
        set
        {
            this.dOBField = value;
        }
    }

    /// <remarks/>
    public string CountryName
    {
        get
        {
            return this.countryNameField;
        }
        set
        {
            this.countryNameField = value;
        }
    }

    /// <remarks/>
    public string StateName
    {
        get
        {
            return this.stateNameField;
        }
        set
        {
            this.stateNameField = value;
        }
    }

    /// <remarks/>
    public string DLNumber
    {
        get
        {
            return this.dLNumberField;
        }
        set
        {
            this.dLNumberField = value;
        }
    }

    /// <remarks/>
    public string IssuingId
    {
        get
        {
            return this.issuingIdField;
        }
        set
        {
            this.issuingIdField = value;
        }
    }

    /// <remarks/>
    public string DOI
    {
        get
        {
            return this.dOIField;
        }
        set
        {
            this.dOIField = value;
        }
    }

    /// <remarks/>
    public string ValidTill
    {
        get
        {
            return this.validTillField;
        }
        set
        {
            this.validTillField = value;
        }
    }

    /// <remarks/>
    public string COV1
    {
        get
        {
            return this.cOV1Field;
        }
        set
        {
            this.cOV1Field = value;
        }
    }

    /// <remarks/>
    public string COV2
    {
        get
        {
            return this.cOV2Field;
        }
        set
        {
            this.cOV2Field = value;
        }
    }
}
